import { existsSync, mkdirSync, rmSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const outputDir = path.join(repoRoot, '.tmp-worker-build');
const outputFile = path.join(outputDir, 'index.js');

if (existsSync(outputDir)) {
  rmSync(outputDir, { recursive: true, force: true });
}
mkdirSync(outputDir, { recursive: true });

try {
  execSync('npx wrangler@4 pages functions build --outdir=.tmp-worker-build --output-config-path=.tmp-worker-build/wrangler.json', {
    cwd: repoRoot,
    stdio: 'inherit'
  });
} catch (error) {
  process.exit(1);
}

if (!existsSync(outputFile)) {
  console.error(`Worker bundle was not generated at ${outputFile}`);
  process.exit(1);
}

// Generate a wrapper entry point that re-exports the Pages Functions default
// fetch handler AND the OnlineSessionsDO Durable Object class so that
// `wrangler deploy` can see both the fetch handler and the DO export.
const wrapperContent = [
  '// Auto-generated by build-worker.mjs – do not edit manually.',
  '// Re-exports the Pages Functions fetch handler and the OnlineSessionsDO',
  '// Durable Object class so wrangler can bind both in a single Worker.',
  'export { default } from \'./index.js\';',
  'export { OnlineSessionsDO } from \'../functions/api/admin/OnlineSessionsDO\';',
].join('\n') + '\n';

const { writeFileSync } = await import('node:fs');
writeFileSync(path.join(outputDir, 'worker-entry.ts'), wrapperContent, 'utf-8');
console.log('Generated .tmp-worker-build/worker-entry.ts');
